# fly.toml app configuration file generated for ra-timecard-recorder on 2023-11-18T19:20:45+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ra-timecard-recorder"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
TZ = "Asia/Tokyo"

[[vm]]
# instance will be free of charge iff size == "shared-cpu-1x" and memory == "256mb"
size = "shared-cpu-1x"
memory = "256mb"
