version: '3'
services:
  db:
    image: postgres:latest
    container_name: ra_timecard_recorder_dev_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
